"""add pdf_drive_file_id to papers

Revision ID: f647c3365cd3
Revises: 2e0aa70ceec2
Create Date: 2026-02-19 11:20:56.141969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f647c3365cd3'
down_revision: Union[str, None] = '2e0aa70ceec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_drive_file_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('pdf_drive_file_id')

    # ### end Alembic commands ###
